### ISSUE TITLE
Double size of outer bounds

### ISSUE THREAD

**Issue by ximex** [ebrelsford/Leaflet.snogylop#1]
is it right that the outer bounds of the (multi)polygon is the bbox of the current view?
if you zoom out you could see this bounds for short time. maybe double the size of this bound that you didn't see it if you only zoom out one zoom level.

**Comment by nrenner** [comment]
The outer bounds with unfilled areas outside, observed while panning and zooming out, are those of the vector renderer. The renderer bounds are limited to the map view plus some buffer, that can be adjusted with the [padding](https://leafletjs.com/reference-1.4.0.html#renderer-padding) option.

With a padding of 1 (size of map view in each direction; default 0.1), the undesired effect is mostly gone:
```js
L.geoJson(data, {
    invert: true,
    renderer: L.svg({ padding: 1 })
}).addTo(map);
```

By assigning a new renderer instance (since Leaflet 1.0), this doesn't affect other vector layers, see also second [SVG Usage example](https://leafletjs.com/reference-1.4.0.html#svg).

**Comment by ebrelsford** [comment]
@nrenner This is a great tip, thank you for it!
